services:
  db: #имя ресурса/службы
    image: postgres:16.1 #название образа и его вресия
    environment: #определение переменных среды, которые будут установлены в контейнере
      POSTGRES_USER: admin #определение имени пользователя
      POSTGRES_PASSWORD: h646yNIK #определение пороля пользователя
      POSTGRES_DB: carnumbers
      PGDATA: /data/postgres #опциональная переменная, которая определяет, где будет находится бд внутри контейнера

    volumes: #список хранилищ, который является промежутком для выделения постоянных мест хранения бд
      - ./postgres:/data/postgres #определение общей папки, где находится всё, что связано с postgres
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql #определение файлы, который инициализирует бд
    ports: #список портов, который является промежутком между портами контейнера и операционной системой
      - "9999:5432"